import type { MetadataRoute } from "next";

/* ═══════════════════════════════════════════════════════════
   SITEMAP.XML — Auto-generated by Next.js
   
   Tells Google + other crawlers about all pages on the site
   Accessible at: https://rikriti.in/sitemap.xml
   ═══════════════════════════════════════════════════════════ */

const SITE_URL = "https://rikriti.in";

export default function sitemap(): MetadataRoute.Sitemap {
  const currentDate = new Date();

  return [
    {
      url: SITE_URL,
      lastModified: currentDate,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/collections`,
      lastModified: currentDate,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    // Section anchors on homepage (helps search engines understand structure)
    {
      url: `${SITE_URL}/#hot-drops`,
      lastModified: currentDate,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/#story`,
      lastModified: currentDate,
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/#reviews`,
      lastModified: currentDate,
      changeFrequency: "weekly",
      priority: 0.5,
    },
  ];
}